version: 2
jobs:
  build:
    working_directory: ~/workspace
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependency
          command: sudo apt-get update && sudo apt-get install jq
      - run:
          name: Configure aws
          command: aws configure set default.region eu-west-1
      - run:
          name: Push to S3
          command: aws deploy push --application-name deeperview --s3-location s3://artefacts.ft-konpolicygenerator/codedeploy_test/deeperview-${CIRCLE_BUILD_NUM}.zip --source ~/workspace
      - run:
          name: Create-deployment
          command: deployment_id_json=`aws deploy create-deployment --application-name deeperview --s3-location bucket=artefacts.ft-konpolicygenerator,key=codedeploy_test/deeperview-${CIRCLE_BUILD_NUM}.zip,bundleType=zip --deployment-group-name deeperview_DG`
      - run:
          name: extract deployment id
          command: |
            echo "json is $deployment_id_json
            deployment_id=`echo $deployment_id_json| jq ".deploymentId"`
            echo $deployment_id
      - run:
          name: Get deployment status
          command: aws deploy get-deployment --deployment-id $deployment_id
