version: 2
jobs:
  build:
    working_directory: ~/workspace
    machine: true
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Push to S3
          command: aws deploy push --application-name deeperview --s3-location s3://dev.ft.dw.load.mohammed.test/deeperview.zip --source ~/workspace
